default:
  before_script:
    - date
    - ls
    - yum install -y python3
    - python3 -V
    - source ./setup.sh

single_bin:
  script:
    - ./utils/compute_fast_limits.py -m doc/tutorials/counting_limit/inputs/simple_counting.json
       -y nsig=0.5:nsig=1:nsig=1.5:nsig=2:nsig=2.5:nsig=3:nsig=3.5:nsig=4:nsig=5:nsig=6
       -n 100 -o simple_counting_toys -b 2
