default:
  before_script:
    - date

single_bin:
  script:
    - ls
    - sudo apt-get update -qq && sudo apt-get install -y python3
    - source ./setup.sh
    - ../utils/compute_fast_limits.py -m inputs/simple_counting.json \
       -y nsig=0.5:nsig=1:nsig=1.5:nsig=2:nsig=2.5:nsig=3:nsig=3.5:nsig=4:nsig=5:nsig=6 \
       -n 100 -o simple_counting_toys -b 2
