default:
  before_script:
    - date
    - ls
    - yum install -y python3
    - python3 -V
    - pip install --upgrade pip
    - source ./setup.sh

single_bin_limit:
  script:       
    - testing/single_bin_limit/run.sh > out.log
    - testing/single_bin_limit/diff.sh out.log testing/single_bin_limit/ref.log
    
multi_channel_limit:
  script:
    - testing/multi_channel_limit/run.sh > out.log
    - testing/multi_channel_limit/diff.sh out.log testing/multi_channel_limit/ref.log
