default:
  before_script:
    - date
    - ls
    - yum install -y python3
    - python3 -V
    - export NO_DOC=True
    - source ./setup.sh
    - echo "Setup done"

fit_covmat:
  script:
    - testing/fit_covmat/run.sh > out.log
    - testing/fit_covmat/diff.sh out.log testing/fit_covmat/ref.log

single_bin_limit:
  script:
    - testing/single_bin_limit/run.sh > out.log
    - testing/single_bin_limit/diff.sh out.log testing/single_bin_limit/ref.log

multi_channel_limit:
  script:
    - testing/multi_channel_limit/run.sh > out.log
    - testing/multi_channel_limit/diff.sh out.log testing/multi_channel_limit/ref.log

poi_scan_1d:
  script:
    - testing/poi_scan_1d/run.sh > out.log
    - testing/poi_scan_1d/diff.sh out.log testing/poi_scan_1d/ref.log

poi_scan_2d:
  script:
    - testing/poi_scan_2d/run.sh > out.log
    - testing/poi_scan_2d/diff.sh out.log testing/poi_scan_2d/ref.log

poi_scan_timing:
  script:
    - testing/poi_scan_timing/run.sh > out.log
    - testing/poi_scan_timing/diff.sh out.log testing/poi_scan_timing/ref.log

reparam:
  script:
    - testing/reparam/run.sh > out.log
    - testing/reparam/diff.sh out.log testing/reparam/ref.log

prune_nps:
  script:
    - testing/prune_nps/run.sh > out.log
    - testing/prune_nps/diff.sh out.log testing/prune_nps/ref.log

check_expressions:
  script:
    - testing/check_expressions/run.sh > out.log
    - testing/check_expressions/diff.sh out.log testing/check_expressions/ref.log
